<a href="https://colab.research.google.com/github/LBQTrung/Python-exercise/blob/main/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sử dụng thư viện Numpy



In [ ]:
import numpy as np

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [ ]:
np.arange(start = -15, stop = 27, step = 0.7)

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [ ]:
np.random.normal(loc = 2.7, scale = 1.2, size = 40)

array([4.71885181, 3.62830261, 1.87074605, 2.83177199, 2.94086489,
       2.5630202 , 2.96061011, 6.37564223, 2.3051536 , 3.17673186,
       3.90467296, 2.68391553, 3.0886324 , 2.49405429, 3.36922209,
       4.36573987, 3.41233022, 3.52265984, 1.44645906, 3.83505104,
       2.86480646, 1.98946158, 2.40303224, 3.36286655, 4.15443415,
       3.38567658, 3.56744729, 0.89009649, 2.69710803, 1.39074195,
       2.25832398, 3.46221635, 4.08705066, 1.13257929, 2.57076785,
       3.90580362, 2.01082903, 2.08961867, 3.78615395, 3.47791269])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [ ]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'],
                 size = 17)

array(['Russia', 'France', 'Russia', 'Britain', 'Viet Nam', 'France',
       'Singapore', 'Singapore', 'Singapore', 'France', 'Singapore',
       'Russia', 'Singapore', 'Britain', 'Singapore', 'Russia', 'Britain'],
      dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [ ]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'],
                 size = 17,
                 p= [0.6, 0.1, 0.1, 0.1, 0.1])

array(['Singapore', 'Singapore', 'Britain', 'Viet Nam', 'Singapore',
       'Viet Nam', 'Viet Nam', 'Viet Nam', 'Viet Nam', 'Britain',
       'Viet Nam', 'Viet Nam', 'Viet Nam', 'Viet Nam', 'Viet Nam',
       'Britain', 'Viet Nam'], dtype='<U9')

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên



In [ ]:
from scipy import stats

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [ ]:
stats.norm.rvs(loc = 12.7, scale = 2.6, size = 30)

array([13.30901009, 10.41583754, 14.21695703,  9.49524502, 10.26353501,
       17.43490018,  8.03984396, 12.57342643, 15.21367965, 12.31496036,
       12.38552102, 15.44057036, 10.81470828, 14.13060287, 12.59891584,
       12.60511166, 13.63815575,  8.42453285, 15.9274302 ,  9.90609231,
       11.79123842, 13.04335233, 14.70102446, 15.46201702, 13.94296733,
       12.14424782, 10.63313464, 10.94322125, 13.70829259, 10.88161188])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [ ]:
np.random.seed(10)
a= stats.poisson.rvs(mu = 50,
                    size = 100)